#!/bin/bash
cd /opt
sudo wget http://sourceforge.net/projects/xampp/files/XAMPP%20Linux/5.5.28/xampp-linux-x64-5.5.28-0-installer.run/download -O xampp-linux-x64-5.5.28-0-installer.run
sudo chmod +x xampp-linux-x64-5.5.28-0-installer.run
sudo ./xampp-linux-x64-5.5.28-0-installer.run
